version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "piggy-nosnap"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8opmwdk7jons"
s3_prefix = "piggy-nosnap"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
